### ISSUE TITLE
Infinitely scalable?

### ISSUE THREAD

**Issue by Charuru** [mafintosh/webrtc-swarm#7]
I'm looking to create a p2p chatroom with infinite scalability. Basically right now I'm paying pusher.com a lot of money to scale my chat app which has hundreds of users in a single room. Is this the library that I want? Some more details in the readme would be great.

**Comment by paulkernfeld** [comment]
I think this could be a useful basis for your chatroom, but you'd need something more. In [this thread](https://github.com/feross/webtorrent/issues/288) and probably elsewhere, there are some interesting notes on the maximum number of RTC connections that can be open (about 30 for Chrome). So, in order to build a highly scalable chatroom, you'd need a clever way to propagate chat messages around the room, since you can't connect every client to every other client. Perhaps you could use a gossip protocol to accomplish that.

**Comment by Charuru** [comment]
Oh I see, I thought this was a gossip protocol. Thanks.

**Comment by perguth** [comment]
Thanks @paulkernfeld for the good answer!
